name: smote
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - openpyxl
  - pip
  - wheel
  - tzdata
  - python-dateutil
  - pytz
  - bottleneck
  - mkl
  - mkl-service
  - numexpr
  - bzip2
  - zlib
  - sqlite
  - tk
  - pip:
      - annotated-types==0.7.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.60.1
      - idna==3.11
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - liac-arff==2.5.0
      - matplotlib==3.10.7
      - minio==7.2.18
      - numpy==2.2.6
      - openml==0.15.1
      - packaging==25.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - pyarrow==22.0.0
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyparsing==3.2.5
      - requests==2.32.5
      - scikit-learn==1.6.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - xmltodict==1.0.2
